controller_manager:
  ros__parameters:
    # update_rate 这里不使用浮点数
    update_rate: 100  # Hz 这里从100调整到50试试
    use_sim_time: true

    # 我觉得在bridge里使用了joint_state_broadcaster，所以这里不需要再使用，试试,不行
    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    fishbot_effort_controller:
      type: effort_controllers/JointGroupEffortController
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      # enable_stamped_cmd_vel: true # 此处也作为尝试取消时间戳的尝试

      # 这行是根据vscode建议添加的，我的设想是让差速器订阅cmd_vel话题，这样在nav2发布的cmd_vel话题就可以直接控制差速器了,不确定能行吗,等下试试
      # cmd_vel_topic: cmd_vel

fishbot_effort_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

fishbot_diff_drive_controller:
  ros__parameters:
    # enable_stamped_cmd_vel: true # 此处也作为尝试取消时间戳的尝试,没有作用，cmd_vel仍然是twist，fishbot_diff_drive仍然是twiststamped

    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.20
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.032

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # publish_rate由50改为1000
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # 由帮助文档添加来
    linear.x.max_velocity: .NAN
    linear.x.min_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_deceleration: .NAN
    linear.x.max_acceleration_reverse: .NAN
    linear.x.max_deceleration_reverse: .NAN
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.min_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_deceleration: .NAN
    angular.z.max_acceleration_reverse: .NAN
    angular.z.max_deceleration_reverse: .NAN
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN

 
    
