<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>"
    <xacro:macro name="base_xacro" params="length radius">
                
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
            <!-- 此处质量的单位是kg，采用国际单位制 -->
        </link>
        
        <link name="base_footprint" />
        <!-- 后面带有一个空部件base_footprint，这个空部件是为了方便机器人的定位，不会影响机器人的运动，只是用来定位机器人的位置。 -->

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0 0 0"/>
            <!-- 让base_link固定在base_footprint空部件的上方，高度设置为机器人身体高度的一半加上轮子的半径，再稍减去1mm，使轮子看起来紧贴地面 -->
            <!-- 定义了关节的原点（origin），即子链接相对于父链接的位置和姿态-->
        </joint>
    </xacro:macro>
</robot>